## Упражнения по библиотеке Numpy

In [2]:
import numpy as np



**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.random.randint(0, 10, size=10)

new_arr = np.where((arr > 3) & (arr < 8), -arr, arr)
print(arr)
print(new_arr)



[3 5 2 4 7 9 5 9 7 8]
[ 3 -5  2 -4 -7  9 -5  9 -7  8]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.random.randint(0, 10, size=10)

new_arr = np.where(arr == arr.max(), 0, arr)

print(arr)
print(new_arr)

[3 4 6 0 8 1 1 6 5 2]
[3 4 6 0 0 1 1 6 5 2]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

grids = np.meshgrid(*arr, indexing='ij')
stacked = np.stack(grids, axis=-1)
new_arr = stacked.reshape(-1, arr.shape[0])

print(arr)
print(new_arr)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.array([
    [1, 3, 2],
    [2, 3, 4],
    [1, 2, 4],
    [2, 3, 5],
    [1, 3, 4],
    [0, 1, 2],
    [2, 3, 6],
    [1, 2, 5]
])

B = np.array([
    [1, 2],
    [2, 3]
])

eq = A[:, :, None, None] == B[None, None, :, :]

contains_each_B_row = eq.any(axis=1).all(axis=2)

mask = contains_each_B_row.all(axis=1)

result = A[mask]
print(mask)
print(result)

[ True False False False False False False False]
[[1 3 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
arr = np.array([
    [1, 3, 2],
    [2, 3, 4],
    [1, 2, 4],
    [2, 3, 5],
    [1, 3, 4],
    ['a', 'a', 'a'],
    [9, 9, 9],
    [0, 0, 0],
    [1, 1, 1],
    [2, 2, 2]
])

same_as_first = (arr == arr[:, [0]]).all(axis=1)
mask = ~same_as_first
result = arr[mask]

print(arr)
print()
print(result)

[['1' '3' '2']
 ['2' '3' '4']
 ['1' '2' '4']
 ['2' '3' '5']
 ['1' '3' '4']
 ['a' 'a' 'a']
 ['9' '9' '9']
 ['0' '0' '0']
 ['1' '1' '1']
 ['2' '2' '2']]

[['1' '3' '2']
 ['2' '3' '4']
 ['1' '2' '4']
 ['2' '3' '5']
 ['1' '3' '4']]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
arr = np.array([
    [1, 3, 2],
    [2, 3, 4],
    [1, 2, 4],
    [2, 3, 5],
    ['a', 'a', 'a'],
    ['a', 'a', 'a'],
    [0, 0, 0],
    [0, 0, 0],
    [1, 1, 1],
    [1, 1, 1]
])

import numpy as np

unique_rows = np.unique(arr, axis=0)
unique_rows

print(arr)
print()
print(unique_rows)

[['1' '3' '2']
 ['2' '3' '4']
 ['1' '2' '4']
 ['2' '3' '5']
 ['a' 'a' 'a']
 ['a' 'a' 'a']
 ['0' '0' '0']
 ['0' '0' '0']
 ['1' '1' '1']
 ['1' '1' '1']]

[['0' '0' '0']
 ['1' '1' '1']
 ['1' '2' '4']
 ['1' '3' '2']
 ['2' '3' '4']
 ['2' '3' '5']
 ['a' 'a' 'a']]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
X = [
    [1, 0, 1],
    [2, 0, 2],
    [3, 0, 3],
    [4, 4, 4]
]

## Python way
mult1 = 1
for i in range(min(len(X), len(X[0]))):
    if X[i][i] != 0:
        mult1 *= X[i][i]
print(mult1)

## Numpy way
d = np.diag(X)
mult2 = np.prod(d[d != 0])

print(mult2)


3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

## Python way
flag = False
if len(x) == len(y) and sorted(x) == sorted(y):
    flag = True
print(flag)

## Numpy way
flag2 = False
x = np.asarray(x)
y = np.asarray(y)
if x.size != y.size:
    flag2 = False
if x.size == y.size and np.array_equal(np.sort(x), np.sort(y)):
    flag2 = True
print(flag2)
    

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [11]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

## Python way
after_zero = []
for i in range(1, len(x)):
    if x[i - 1] == 0:
        after_zero.append(x[i])
print(max(after_zero))

## Numpy way
x = np.asarray(x)
mask = (x[:-1] == 0)
result = x[1:][mask].max()
print(result)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
x = [2, 2, 2, 3, 3, 3, 5]

## Python way
values = []
summ = []
current = x[0]
cnt = 1

for i in range(1, len(x)):
    if x[i] == current:
        cnt += 1
    else:
        values.append(current)
        summ.append(cnt)
        current = x[i]
        cnt = 1

values.append(current)
summ.append(cnt)

print(values) 
print(summ)

## Numpy way
x = np.asarray(x)
indexes = np.where(np.diff(x) != 0)[0] + 1
values2 = x[np.concatenate(([0], indexes))]
summ2 = np.diff(np.concatenate(([0], indexes, [x.size])))

print(values2) 
print(summ2)


[2, 3, 5]
[3, 3, 1]
[2 3 5]
[3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [13]:
import math
from scipy.spatial.distance import cdist
from timeit import timeit

x = [(1, 2), (3, 4)]
y = [(5, 6), (7, 8)]

## Python way
result1 = []

for a in x:
    row = []
    for b in y:
        sq = 0
        for i in range(len(b)):
            diff = a[i] -b[i]
            sq += diff * diff
        row.append(math.sqrt(sq))
    result1.append(row)
print("Python result:")
print(result1)

## Numpy way

xx = np.array(x)
yy = np.array(y)

diff = xx[:, None, :] - yy[None, :, :]
sq2 = diff ** 2
result2 = np.sqrt(sq2.sum(axis=2))

print("Numpy result:")
print(result2)


## Speed test

n, m, d = 1000, 1000, 32
X = np.random.randn(n, d)
Y = np.random.randn(m, d)

def numpy_dist():
    diff = X[:, None, :] - Y[None, :, :]
    return np.sqrt((diff * diff).sum(axis=2))

def scipy_dist():
    return cdist(X, Y, metric="euclidean")


t_np = timeit(numpy_dist, number=5)
t_sp = timeit(scipy_dist, number=5)
print()
print("NumPy spped:", t_np, "sec")
print("SciPy speed:", t_sp, "sec")

Python result:
[[5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381]]
Numpy result:
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]

NumPy spped: 1.6245603999996092 sec
SciPy speed: 0.13655839999955788 sec


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [15]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [16]:

average_calories = calorie_stats.mean() - 60
print(average_calories)


46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [17]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [18]:

median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [19]:
a = 1
nth_percentile = np.percentile(calorie_stats, a)
print(f'Percentile {a}: {nth_percentile}')

a = 3

nth_percentile = np.percentile(calorie_stats, a)
print(f'Percentile {a}: {nth_percentile}')

a = 6
nth_percentile = np.percentile(calorie_stats, a)
print(f'Percentile {a}: {nth_percentile}')

Percentile 1: 50.0
Percentile 3: 55.599999999999994
Percentile 6: 75.6


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [20]:

more_calories = np.mean(calorie_stats > 60) * 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [24]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [25]:
text = """
Данные показывают, что почти все продукты конкурентов содержат больше калорий, чем CrunchieMunchies. В большинстве продукты конкурентов содержат от 90 до 125 каллорий. 
CrunchieMunchies выгодно выделяются на этом фоне, имея всего 60 калорий в одной порции.
В маркетинге компания может использовать эти цифры, чтобы подчеркнуть, что их продукт содержит значительно меньше калорий в сравнении с большинством альтернатив на рынке и является более healthy.
"""

print(text)


Данные показывают, что почти все продукты конкурентов содержат больше калорий, чем CrunchieMunchies. В большинстве продукты конкурентов содержат от 90 до 125 каллорий. 
CrunchieMunchies выгодно выделяются на этом фоне, имея всего 60 калорий в одной порции.
В маркетинге компания может использовать эти цифры, чтобы подчеркнуть, что их продукт содержит значительно меньше калорий в сравнении с большинством альтернатив на рынке и является более healthy.

